markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: My blog
description: 
keywords: 
url: http://horizon0514.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: horizon huang
    email: horizon0514@gmail.com
    imageLink: http://ent.51oscar.com/Public/Home/ueditor/php/upload/56311372666771.jpg
    simpleIntro : 一个奇怪的、矛盾的个体，正在往前狂奔。 
    detailIntro:
        <p>hello world</p>
        <p>不知道如何自我介绍，于是打上tag吧，通过tag来说我是谁。</p>
        <p>BUPTer,kindler,Androider,Ubuntuer,Instagramer.</p>
        <p>小时候读书如饥似渴，却没有什么书读。现在很多书，却完全静不下来。选择了技术这条“不归路”,不知道自己能不能到达终点。且行且珍惜！</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/horizon0514
  - class: icon-github-alt
    url: http://github.com/horizon0514
  - class: icon-twitter
    url: http://twitter.com/horizon0514
  - class: icon-google-plus
    url: http://plus.google.com/horizon0514
  - class: icon-instagram
    url: http://instagram.com/horizon0514

#Links
customLinks:
  - item:
    - text: horizon0514
      url: http://horizon0514.github.io
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: 

#comment config
disqus:
  config: false
  id: 

duoshuo:
  config: true
  id: horizon0514 
