markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://horizon0514.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: horizon huang
    email: horizon0514@gmail.com
    imageLink: http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    simpleIntro : nothing
    detailIntro:
        <p>hello world</p>
#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/pizn
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/pizn
  - class: icon-twitter
    url: http://twitter.com/piznlin
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: horizon0514
      url: http://horizon0514.github.io
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: zhanxin
